'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const motion=()=>window.gsap&&!reduced.matches;
const videos=$$('main video');
function loadVideo(v){if(v.dataset.src){v.src=v.dataset.src;delete v.dataset.src;v.load();}else if(v.querySelector('source[data-src]')){v.querySelectorAll('source[data-src]').forEach(s=>{s.src=s.dataset.src;delete s.dataset.src;});v.load();}}
function updateVideoControl(v){const b=$(`[data-target="${v.id}"]`);if(!b)return;b.innerHTML=v.paused?'REPRODUCIR <span>▷</span>':'PAUSAR <span>Ⅱ</span>';b.setAttribute('aria-label',`${v.paused?'Reproducir':'Pausar'} vídeo ${v.id==='hero-video'?'de portada':'del oficio'}`);}
function playVideo(v){loadVideo(v);const p=v.play();if(p)p.catch(()=>updateVideoControl(v));}
videos.forEach(v=>{v.addEventListener('play',()=>updateVideoControl(v));v.addEventListener('pause',()=>updateVideoControl(v));v.addEventListener('error',()=>updateVideoControl(v));});
$$('.video-toggle').forEach(b=>b.addEventListener('click',()=>{const v=$('#'+b.dataset.target);if(v.paused){v.dataset.userPaused='false';playVideo(v);}else{v.dataset.userPaused='true';v.pause();}}));
const observer=new IntersectionObserver(entries=>entries.forEach(({target:v,isIntersecting})=>{v.dataset.inView=String(isIntersecting);if(isIntersecting&&!reduced.matches&&v.dataset.userPaused!=='true'&&!document.hidden&&!document.querySelector('dialog[open]'))playVideo(v);else v.pause();}),{threshold:.2});videos.forEach(v=>observer.observe(v));
function resumeVisibleVideos(){videos.forEach(v=>{if(v.dataset.inView==='true'&&!reduced.matches&&v.dataset.userPaused!=='true'&&!document.hidden)playVideo(v);});}
document.addEventListener('visibilitychange',()=>document.hidden?videos.forEach(v=>v.pause()):resumeVisibleVideos());reduced.addEventListener('change',()=>reduced.matches?videos.forEach(v=>v.pause()):resumeVisibleVideos());
const menu=$('#menu'),menuButton=$('.menu-toggle');
menuButton.addEventListener('click',()=>{menu.showModal();menuButton.setAttribute('aria-expanded','true');videos.forEach(v=>v.pause());if(motion()){gsap.fromTo(menu,{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)',duration:.65,ease:'power4.inOut'});gsap.fromTo('#menu nav a',{y:70,opacity:0},{y:0,opacity:1,duration:.7,stagger:.08,delay:.25,ease:'power4.out',clearProps:'all'});}});
function closeMenu(){if(motion())gsap.to(menu,{clipPath:'inset(0 0 100% 0)',duration:.4,ease:'power3.inOut',onComplete:()=>{menu.close();gsap.set(menu,{clearProps:'all'});}});else menu.close();}
$('.close-menu').addEventListener('click',closeMenu);$$('#menu nav a').forEach(a=>a.addEventListener('click',closeMenu));menu.addEventListener('close',()=>{menuButton.setAttribute('aria-expanded','false');resumeVisibleVideos();});
const projects={nercon:{title:'NERCÓN',status:'Vivienda terminada · Chiloé',description:'Madera, revestimiento oscuro y una cubierta que define su carácter. El resultado de una obra construida paso a paso.',images:[['nercon','Casa terminada en Nercón']],source:'p/DbEJO8hCR6Q/'},notuco:{title:'NOTUCO',status:'Registro de obras · enero de 2023',description:'Viviendas publicadas por el equipo durante sus obras en Notuco. Distintas vistas de su arquitectura, revestimientos y relación con el terreno.',images:[['notuco-2023-1','Viviendas en Notuco'],['notuco-2023-2','Vista de vivienda en Notuco'],['notuco-2023-3','Detalle exterior de vivienda en Notuco']],source:'p/Cnerae2uaBe/'},tara:{title:'TARA',status:'Obra en desarrollo · Chonchi',description:'La estructura y la cubierta toman forma. Una vista del avance en terreno, antes de completar la vivienda.',images:[['tara','Vista aérea de la obra de Tara']],source:'p/DcWnSH4gRk9/'},huicha:{title:'HUICHA',status:'Vivienda entregada · Chiloé',description:'Un recorrido por la casa, sus espacios de madera y el paisaje que la rodea. Registro visual de la publicación original, sin audio.',film:'assets/video/recorrido-huicha.mp4',source:'reel/DZdzTd8JWX0/'}};
const gallery=$('#gallery');let currentProject,index=0;
function renderImage(){const [name,alt]=currentProject.images[index];$('#gallery-image').src=`assets/${name}.webp`;$('#gallery-image').alt=alt;$('#gallery-count').textContent=`${index+1} / ${currentProject.images.length}`;$('#previous').disabled=index===0;$('#next').disabled=index===currentProject.images.length-1;if(motion())gsap.fromTo('#gallery-image',{opacity:.4,scale:1.025},{opacity:1,scale:1,duration:.5,ease:'power2.out',clearProps:'all'});}
function openProject(name){currentProject=projects[name];index=0;$('#gallery-title').textContent=currentProject.title;$('#gallery-status').textContent=currentProject.status;$('#gallery-description').textContent=currentProject.description;$('#gallery-source').href=`https://www.instagram.com/gomez_y_gomez_construcciones/${currentProject.source}`;const isFilm=!!currentProject.film;$('#gallery-image').hidden=isFilm;$('#gallery-video').hidden=!isFilm;$('.gallery-controls').hidden=isFilm;if(isFilm){$('#gallery-video').src=currentProject.film;$('#gallery-video').poster='assets/huicha.webp';}else renderImage();gallery.showModal();videos.forEach(v=>v.pause());if(isFilm)$('#gallery-video').play().catch(()=>{});if(motion())gsap.fromTo(gallery,{opacity:0,y:35},{opacity:1,y:0,duration:.5,ease:'power3.out',clearProps:'all'});}
$$('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)));$$('[data-film]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.film)));$('.close-gallery').addEventListener('click',()=>gallery.close());$('.gallery-contact').addEventListener('click',()=>gallery.close());gallery.addEventListener('close',()=>{$('#gallery-video').pause();$('#gallery-video').removeAttribute('src');$('#gallery-video').load();resumeVisibleVideos();});$('#previous').addEventListener('click',()=>{if(index>0){index--;renderImage();}});$('#next').addEventListener('click',()=>{if(index<currentProject.images.length-1){index++;renderImage();}});gallery.addEventListener('keydown',e=>{if(currentProject.film)return;if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#previous').click();});
const craftData=[{title:'MANOS QUE\nSABEN HACER.',text:'Un equipo que trabaja junto en terreno. Cortar, ajustar y montar con atención a cada pieza.',file:'equipo',poster:'equipo',alt:'El equipo trabajando en la estructura de madera'},{title:'MEDIR BIEN.\nCONSTRUIR MEJOR.',text:'El nivel óptico ayuda a revisar las alturas desde la base. La precisión empieza mucho antes de las terminaciones.',file:'precision',poster:'precision',alt:'Nivel óptico en acción durante la obra'},{title:'UNA CASA,\nPASO A PASO.',text:'El proceso de una vivienda entregada en Notuco: ver cómo la estructura toma forma también es parte de su historia.',file:'notuco',poster:'notuco',alt:'Proceso de construcción de una vivienda en Notuco'}];let craftIndex=0;
function selectCraft(i){if(i===craftIndex)return;craftIndex=i;const d=craftData[i];$('#craft-title').innerText=d.title;$('#craft-description').textContent=d.text;$('.craft-index').textContent=`0${i+1} — 03`;$$('[data-craft]').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',String(n===i));});const v=$('#craft-video');v.pause();v.src=`assets/video/${d.file}.mp4`;delete v.dataset.src;v.poster=`assets/${d.poster}.webp`;v.setAttribute('aria-label',d.alt);v.load();if(!reduced.matches&&v.dataset.inView==='true'&&v.dataset.userPaused!=='true')playVideo(v);if(motion()){gsap.fromTo('#craft-title,#craft-description',{y:18,opacity:.2},{y:0,opacity:1,stagger:.06,duration:.45,ease:'power3.out',clearProps:'all'});gsap.fromTo(v,{opacity:.3},{opacity:1,duration:.5});}}
let craftManual=false;$$('[data-craft]').forEach(b=>b.addEventListener('click',()=>{craftManual=true;selectCraft(Number(b.dataset.craft));}));
let compareManual=false;
const compareStage=$('.journey-stage'),compareHandle=$('.journey-handle span');
function setCompare(value){value=Math.max(0,Math.min(100,Number(value)));compareStage.style.setProperty('--reveal',value+'%');compareHandle.setAttribute('aria-valuenow',Math.round(value));}
let compareDragging=false;
function dragCompare(e){const bounds=compareStage.getBoundingClientRect();setCompare((e.clientX-bounds.left)/bounds.width*100);}
compareHandle.addEventListener('pointerdown',e=>{compareManual=true;compareDragging=true;compareHandle.setPointerCapture(e.pointerId);dragCompare(e);});
compareHandle.addEventListener('pointermove',e=>{if(compareDragging)dragCompare(e);});
function stopCompare(){compareDragging=false;}
compareHandle.addEventListener('pointerup',stopCompare);
compareHandle.addEventListener('pointercancel',stopCompare);
compareHandle.addEventListener('lostpointercapture',stopCompare);
compareHandle.addEventListener('keydown',e=>{let value=Number(compareHandle.getAttribute('aria-valuenow'));if(e.key==='ArrowRight')value+=5;else if(e.key==='ArrowLeft')value-=5;else if(e.key==='Home')value=0;else if(e.key==='End')value=100;else return;e.preventDefault();compareManual=true;setCompare(value);});
$$('[data-service]').forEach(b=>b.addEventListener('click',()=>{$('#service').value=b.dataset.service;$('#quote-result').hidden=true;$('#service').focus({preventScroll:true});$('#quote-form').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'});}));
$('#quote-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=data.get('nombre').trim(),place=data.get('lugar').trim();if(!name||!place){const field=e.currentTarget.elements[!name?'nombre':'lugar'];field.setCustomValidity('Escribe este dato para preparar la consulta.');field.reportValidity();return;}const message=`Hola, Gómez & Gómez. Soy ${name}.\nMe interesa: ${data.get('servicio')}.\nMi proyecto está en: ${place}.${data.get('detalle').trim()?'\n\n'+data.get('detalle').trim():''}\n\nMe gustaría conversar sobre los próximos pasos.`;$('#quote-preview').textContent=message;$('#whatsapp-link').href=`https://wa.me/56993036179?text=${encodeURIComponent(message)}`;$('#quote-result').hidden=false;$('#whatsapp-link').focus({preventScroll:true});$('#quote-result').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'nearest'});});$$('#quote-form input,#quote-form textarea,#quote-form select').forEach(i=>i.addEventListener('input',()=>{i.setCustomValidity('');$('#quote-result').hidden=true;}));$('#year').textContent=new Date().getFullYear();
if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{
 const intro=gsap.timeline();intro.from('.hero-media',{clipPath:'inset(0 0 100% 0)',duration:1.2,ease:'power4.inOut',clearProps:'clipPath'}).from('.hero h1 span',{y:90,opacity:0,stagger:.13,duration:1,ease:'power4.out',clearProps:'all'},.45).from('.hero-title>p',{y:22,opacity:0,duration:.7,clearProps:'all'},.9);
 gsap.to('.reading-progress',{scaleX:1,ease:'none',scrollTrigger:{trigger:'main',start:'top top',end:'bottom bottom',scrub:true}});
 gsap.to('.hero-title',{y:-70,opacity:.25,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom 25%',scrub:1}});
 gsap.from('.about-heading h2',{y:70,duration:1.1,ease:'power4.out',scrollTrigger:{trigger:'.about',start:'top 75%',once:true},clearProps:'transform'});
 gsap.from('.portrait',{clipPath:'inset(12% 10% 0 10%)',duration:1.3,ease:'power3.out',scrollTrigger:{trigger:'.portrait',start:'top 85%',once:true},clearProps:'clipPath'});
 gsap.fromTo('.statement span',{x:80},{x:-220,ease:'none',scrollTrigger:{trigger:'.statement',start:'top bottom',end:'bottom top',scrub:1}});
 gsap.from('.featured-work',{clipPath:'inset(0 8% 0 8%)',ease:'none',scrollTrigger:{trigger:'.featured-work',start:'top 85%',end:'top 20%',scrub:1},clearProps:'clipPath'});
 $$('.secondary-works article').forEach((el,i)=>gsap.from(el,{y:70+i*45,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%',once:true},clearProps:'transform'}));
 const path=$('.measurement path');const length=path.getTotalLength();gsap.fromTo(path,{strokeDasharray:length,strokeDashoffset:length},{strokeDashoffset:0,duration:2,ease:'power2.inOut',scrollTrigger:{trigger:'.craft-stage',start:'top 65%',once:true}});
 ScrollTrigger.create({trigger:'.journey-stage',start:'top 80%',end:'bottom 35%',onUpdate:s=>{if(!compareManual)setCompare(Math.round(s.progress*100));}});
 });mm.add('(min-width: 1101px) and (prefers-reduced-motion: no-preference)',()=>{ScrollTrigger.create({trigger:'.craft-stage',start:'top 92px',end:'+=1100',pin:true,anticipatePin:1,onUpdate:s=>{if(!craftManual)selectCraft(Math.min(2,Math.floor(s.progress*3)));}});});window.addEventListener('load',()=>ScrollTrigger.refresh());
}
